/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Gonzalo Sáez Martí
 */
public class VentanaAhorcado extends javax.swing.JFrame {

    String palabraOculta = "CETYS";
    int numeroDeFallos = 0;
    
    
    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        dibujaImagen(0);
    }

    private void chequeaLetra(String letra){
        letra = letra.toUpperCase();
        String palabraConGuiones = pantalla.getText();
        boolean acierto = false;
        for(int i=0; i<palabraOculta.length(); i++){
            if(palabraOculta.charAt(i) == letra.charAt(0)){
                //TODO quita el guión bajo de la letra correspondiente
                palabraConGuiones = palabraConGuiones.substring(0, 2*i)
                        + letra 
                        + palabraConGuiones.substring(2*i +1);
                acierto = true;
            }
        }
        //Actualizo el valor que se muestra en la pantalla con las
        //letras adivinadas.
        pantalla.setText(palabraConGuiones);
        
        if(!acierto){
            numeroDeFallos++;
            dibujaImagen(numeroDeFallos);
        }
    }
            
            
    private void dibujaImagen(int numeroImagen){
        URL nombreImagen;
        switch (numeroImagen){
            case 0 : nombreImagen = getClass().getResource("/imagenes/ahorcado_0.png"); break;
            case 1 : nombreImagen = getClass().getResource("/imagenes/ahorcado_1.png"); break;
            case 2 : nombreImagen = getClass().getResource("/imagenes/ahorcado_2.png"); break;
            case 3 : nombreImagen = getClass().getResource("/imagenes/ahorcado_3.png"); break;
            case 4 : nombreImagen = getClass().getResource("/imagenes/ahorcado_4.png"); break;
            case 5 : nombreImagen = getClass().getResource("/imagenes/ahorcado_5.png"); break;
            default : nombreImagen = getClass().getResource("/imagenes/ahorcado_fin.png"); break;
        }
        
        int ancho = panelAhorcado.getWidth();
        int alto = panelAhorcado.getHeight();
        ImageIcon miImagen = new ImageIcon(new ImageIcon(nombreImagen).getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        panelAhorcado.setIcon(miImagen);
    }
    
    private void chequeaBoton(JButton miBoton){
        miBoton.setEnabled(false);
        chequeaLetra(miBoton.getText());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        panelAhorcado = new javax.swing.JLabel();
        Letra1 = new javax.swing.JButton();
        Letra2 = new javax.swing.JButton();
        Letra3 = new javax.swing.JButton();
        Letra4 = new javax.swing.JButton();
        Letra5 = new javax.swing.JButton();
        Letra6 = new javax.swing.JButton();
        Letra7 = new javax.swing.JButton();
        Letra8 = new javax.swing.JButton();
        Letra9 = new javax.swing.JButton();
        Letra10 = new javax.swing.JButton();
        Letra11 = new javax.swing.JButton();
        Letra12 = new javax.swing.JButton();
        Letra13 = new javax.swing.JButton();
        Letra14 = new javax.swing.JButton();
        Letra15 = new javax.swing.JButton();
        Letra16 = new javax.swing.JButton();
        Letra17 = new javax.swing.JButton();
        Letra18 = new javax.swing.JButton();
        Letra19 = new javax.swing.JButton();
        Letra20 = new javax.swing.JButton();
        Letra21 = new javax.swing.JButton();
        Letra22 = new javax.swing.JButton();
        Letra23 = new javax.swing.JButton();
        Letra24 = new javax.swing.JButton();
        Letra25 = new javax.swing.JButton();
        Letra26 = new javax.swing.JButton();
        Letra27 = new javax.swing.JButton();
        Letra28 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pantalla.setText("_ _ _ _ _");

        panelAhorcado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Letra1.setText("A");
        Letra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra1MousePressed(evt);
            }
        });

        Letra2.setText("B");
        Letra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra2MousePressed(evt);
            }
        });

        Letra3.setText("C");
        Letra3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra3MousePressed(evt);
            }
        });

        Letra4.setText("D");
        Letra4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra4MousePressed(evt);
            }
        });

        Letra5.setText("E");
        Letra5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra5MousePressed(evt);
            }
        });

        Letra6.setText("F");
        Letra6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra6MousePressed(evt);
            }
        });

        Letra7.setText("G");
        Letra7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra7MousePressed(evt);
            }
        });

        Letra8.setText("N");
        Letra8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra8MousePressed(evt);
            }
        });

        Letra9.setText("H");
        Letra9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra9MousePressed(evt);
            }
        });

        Letra10.setText("I");
        Letra10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra10MousePressed(evt);
            }
        });

        Letra11.setText("J");
        Letra11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra11MousePressed(evt);
            }
        });

        Letra12.setText("K");
        Letra12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra12MousePressed(evt);
            }
        });

        Letra13.setText("L");
        Letra13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra13MousePressed(evt);
            }
        });

        Letra14.setText("M");
        Letra14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra14MousePressed(evt);
            }
        });

        Letra15.setText("T");
        Letra15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra15MousePressed(evt);
            }
        });

        Letra16.setText("Ñ");
        Letra16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra16MousePressed(evt);
            }
        });

        Letra17.setText("O");
        Letra17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra17MousePressed(evt);
            }
        });

        Letra18.setText("P");
        Letra18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra18MousePressed(evt);
            }
        });

        Letra19.setText("Q");
        Letra19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra19MousePressed(evt);
            }
        });

        Letra20.setText("R");
        Letra20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra20MousePressed(evt);
            }
        });

        Letra21.setText("S");
        Letra21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra21MousePressed(evt);
            }
        });

        Letra22.setText("Z");
        Letra22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra22MousePressed(evt);
            }
        });

        Letra23.setText("U");
        Letra23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra23MousePressed(evt);
            }
        });

        Letra24.setText("V");
        Letra24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra24MousePressed(evt);
            }
        });

        Letra25.setText("W");
        Letra25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra25MousePressed(evt);
            }
        });

        Letra26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra26MousePressed(evt);
            }
        });

        Letra27.setText("X");
        Letra27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra27MousePressed(evt);
            }
        });

        Letra28.setText("Y");
        Letra28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra28MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Letra26, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Letra27, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Letra28, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra26, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra27, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra28, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Letra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra1MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra1MousePressed

    private void Letra2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra2MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra2MousePressed

    private void Letra3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra3MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra3MousePressed

    private void Letra4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra4MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra4MousePressed

    private void Letra5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra5MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra5MousePressed

    private void Letra6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra6MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra6MousePressed

    private void Letra7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra7MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra7MousePressed

    private void Letra8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra8MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra8MousePressed

    private void Letra9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra9MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra9MousePressed

    private void Letra10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra10MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra10MousePressed

    private void Letra11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra11MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra11MousePressed

    private void Letra12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra12MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra12MousePressed

    private void Letra13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra13MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra13MousePressed

    private void Letra14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra14MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra14MousePressed

    private void Letra15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra15MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra15MousePressed

    private void Letra16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra16MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra16MousePressed

    private void Letra17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra17MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra17MousePressed

    private void Letra18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra18MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra18MousePressed

    private void Letra19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra19MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra19MousePressed

    private void Letra20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra20MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra20MousePressed

    private void Letra21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra21MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra21MousePressed

    private void Letra22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra22MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra22MousePressed

    private void Letra23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra23MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra23MousePressed

    private void Letra24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra24MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra24MousePressed

    private void Letra25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra25MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra25MousePressed

    private void Letra26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra26MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra26MousePressed

    private void Letra27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra27MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra27MousePressed

    private void Letra28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra28MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_Letra28MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Letra1;
    private javax.swing.JButton Letra10;
    private javax.swing.JButton Letra11;
    private javax.swing.JButton Letra12;
    private javax.swing.JButton Letra13;
    private javax.swing.JButton Letra14;
    private javax.swing.JButton Letra15;
    private javax.swing.JButton Letra16;
    private javax.swing.JButton Letra17;
    private javax.swing.JButton Letra18;
    private javax.swing.JButton Letra19;
    private javax.swing.JButton Letra2;
    private javax.swing.JButton Letra20;
    private javax.swing.JButton Letra21;
    private javax.swing.JButton Letra22;
    private javax.swing.JButton Letra23;
    private javax.swing.JButton Letra24;
    private javax.swing.JButton Letra25;
    private javax.swing.JButton Letra26;
    private javax.swing.JButton Letra27;
    private javax.swing.JButton Letra28;
    private javax.swing.JButton Letra3;
    private javax.swing.JButton Letra4;
    private javax.swing.JButton Letra5;
    private javax.swing.JButton Letra6;
    private javax.swing.JButton Letra7;
    private javax.swing.JButton Letra8;
    private javax.swing.JButton Letra9;
    private javax.swing.JLabel panelAhorcado;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
